// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0IbwfFm5iAONWe3EoP1AcsiFztwsUECc',
    appId: '1:422454591798:web:dfb3a009aae6bad83e3397',
    messagingSenderId: '422454591798',
    projectId: 'shotsense-ai',
    authDomain: 'shotsense-ai.firebaseapp.com',
    storageBucket: 'shotsense-ai.appspot.com',
    measurementId: 'G-35776FLDYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzd8OZeINZ1cMhsGDdMlQJpDZkgQW0z-o',
    appId: '1:422454591798:android:05d5ed66c28493983e3397',
    messagingSenderId: '422454591798',
    projectId: 'shotsense-ai',
    storageBucket: 'shotsense-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgumk9rJwBSQN3xfx0Ubwqtdy6QSKGigc',
    appId: '1:422454591798:ios:b8cf36fdd058f7113e3397',
    messagingSenderId: '422454591798',
    projectId: 'shotsense-ai',
    storageBucket: 'shotsense-ai.appspot.com',
    iosClientId: '422454591798-3hsaeh0r0s4skc9j3g856tlceq1ps77f.apps.googleusercontent.com',
    iosBundleId: 'com.example.shotsense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgumk9rJwBSQN3xfx0Ubwqtdy6QSKGigc',
    appId: '1:422454591798:ios:680a03fc999e27783e3397',
    messagingSenderId: '422454591798',
    projectId: 'shotsense-ai',
    storageBucket: 'shotsense-ai.appspot.com',
    iosBundleId: 'com.example.shotsense.RunnerTests',
  );
}
