// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9qo-RgXdwPHXbxRl93W6CFynbCRiOXok',
    appId: '1:623073582912:web:ab2e48817961287aec24a5',
    messagingSenderId: '623073582912',
    projectId: 'shotsense-f8806',
    authDomain: 'shotsense-f8806.firebaseapp.com',
    storageBucket: 'shotsense-f8806.appspot.com',
    measurementId: 'G-H5JK688WKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv8B8QJgkSkfv0z65w9zenGXzE5Tlkmmw',
    appId: '1:623073582912:android:10569da00c00b5b5ec24a5',
    messagingSenderId: '623073582912',
    projectId: 'shotsense-f8806',
    storageBucket: 'shotsense-f8806.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTBaUaRtrzjuARON6OmKqz3FWAdihDrg0',
    appId: '1:623073582912:ios:8b56567084d4af8aec24a5',
    messagingSenderId: '623073582912',
    projectId: 'shotsense-f8806',
    storageBucket: 'shotsense-f8806.appspot.com',
    androidClientId: '623073582912-lp1vbtu8j8apgdf6snho3ca2jdh6utot.apps.googleusercontent.com',
    iosClientId: '623073582912-180p75sa4h2fi3vkvp3p05jm5oje7sua.apps.googleusercontent.com',
    iosBundleId: 'com.example.shotsense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTBaUaRtrzjuARON6OmKqz3FWAdihDrg0',
    appId: '1:623073582912:ios:cba4e53cd29fd357ec24a5',
    messagingSenderId: '623073582912',
    projectId: 'shotsense-f8806',
    storageBucket: 'shotsense-f8806.appspot.com',
    androidClientId: '623073582912-lp1vbtu8j8apgdf6snho3ca2jdh6utot.apps.googleusercontent.com',
    iosClientId: '623073582912-ru7d0hrmbcbv722o8gjak3b33u589qgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.shotsense.RunnerTests',
  );
}
