name: shotsense
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  font_awesome_flutter: ^10.6.0
  curved_navigation_bar: ^1.0.3
  eva_icons_flutter: ^3.0.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  google_sign_in: ^6.1.6
  sign_in_button: ^3.2.0
  provider: ^6.0.2
  firebase_ml_model_downloader: ^0.2.4+8
  image_picker: ^1.0.5
  video_player: ^2.8.1
  intl: ^0.19.0
  firebase_app_check: ^0.2.1+8
  skeletonizer: ^1.1.2+1
  syncfusion_flutter_charts: ^25.2.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter_native_splash :
    color: "#ffffff"
    image: assets/images/ShotSense-logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
